#!/bin/bash
case "$1" in
  "build")
    docker-compose up --build -d
    ;;
  "cinstall")
    docker-compose exec --user $(id -u) phpproject composer install
    ;;
  "key")
    docker-compose exec --user $(id -u) phpproject php artisan key:generate
    ;;
  "tinker")
    docker-compose exec phpproject php artisan tinker
    ;;
  "uartisan")
    shift
    docker-compose exec --user $(id -u) phpproject php artisan $*
    ;;
  "artisan")
    shift
    docker-compose exec phpproject php artisan $*
    ;;
  "migrate")
    docker-compose exec phpproject php artisan migrate
    ;;
  "rollback")
    docker-compose exec phpproject php artisan migrate:rollback
    ;;
  "seed")
    docker-compose exec phpproject php artisan db:seed
    ;;
  "phpunit")
    shift
    docker-compose exec --user $(id -u) phpproject ./vendor/bin/phpunit $*
    ;;
  "permissions")
    docker-compose exec phpproject chmod +777 -R storage/framework
    docker-compose exec phpproject chmod +777 -R storage/logs
    ;;
  "cc")
    docker-compose exec --user $(id -u) phpproject php artisan config:clear
    docker-compose exec --user $(id -u) phpproject php artisan cache:clear
    docker-compose exec --user $(id -u) phpproject php artisan view:clear
    ;;
  "up")
    docker-compose up -d
    ;;
  "stop")
    docker-compose stop
    ;;
  "down")
    sudo rm -rf docker-storage
    docker-compose down
    ;;
  "destroy")
    docker-compose down
    docker rm -f $(docker ps -a -q)
    docker rmi -f $(docker images -a -q)
    docker volume rm $(docker volume ls -q)
    docker network rm $(docker network ls | tail -n+2 | awk '{if($2 !~ /bridge|none|host/){ print $1 }}')
    ;;
  *)
    echo "You have failed to specify what to do correctly."
    exit 1
    ;;
esac