version: '3'
services:
  phpproject:
    image: project-php
    build:
      context: ""
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./../../code/project:/var/www/web
      - ~/.ssh:/root/.ssh
      - ~/.config/composer/auth.json:/.composer/auth.json

  webproject:
    image: nginx:latest
    volumes:
      - ./../../code/project:/var/www/web
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker-storage/logs/nginx:/var/log/nginx
    ports:
      - 8000:80
    depends_on:
      - phpproject

  mysqlproject:
    build: docker/mysql
    environment:
      MYSQL_DATABASE: 'homestead_project'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - 13306:3306
    volumes:
      - ./docker-storage/mysql:/var/lib/mysql

  postgresqlproject:
    build: docker/postgresql
    restart: always
    environment:
      POSTGRES_DB: 'homestead_project'
      POSTGRES_USER: 'homestead'
      POSTGRES_PASSWORD: 'secret'
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 15432:5432
    volumes:
      - ./docker-storage/postgresql:/var/lib/postgresql/data/pgdata