version: '3'
services:
  phpproject:
    image: project-php
    build:
      context: ""
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./../../code/project:/var/www/web

  webproject:
    image: nginx:latest
    volumes:
      - ./../../code/project:/var/www/web
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./storage/logs/nginx:/var/log/nginx
    ports:
      - 8000:80
    depends_on:
      - phpproject

  dbproject:
    build: docker/db
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'superpass'
    volumes:
      - bddata:/var/lib/mysql

volumes:
  bddata:
    driver: local